# =============================
# PERFIL: DESENVOLVIMENTO
# =============================

# Mostra SQL no console ? útil para aprender o que o Hibernate faz
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Atualiza o schema automaticamente ? conveniente para estudos
spring.jpa.hibernate.ddl-auto=update

# Swagger disponível sem autenticação ? prático para testar
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true