# =============================
# PERFIL: PRODUÇÃO
# =============================

# Nunca expõe SQL em logs de produção
spring.jpa.show-sql=false

# Apenas valida o schema ? nunca altera automaticamente
spring.jpa.hibernate.ddl-auto=validate

# Swagger completamente desabilitado em produção
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false